# Generated by Django 2.2.2 on 2019-07-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20190720_1309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='education',
            name='details',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
