# Generated by Django 2.2.2 on 2019-07-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_auto_20190720_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='details',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
