# Generated by Django 2.2.2 on 2019-08-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
