# Generated by Django 2.2.2 on 2019-11-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_strenghts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Strenghts',
            new_name='Strenght',
        ),
    ]
